apiVersion: v1
kind: Service
metadata:
  name: {{ include "huna-gpt.fullname" . }}
  labels:
    {{- include "huna-gpt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.exposedPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "huna-gpt.selectorLabels" . | nindent 4 }}
